language: generic

sudo: required

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_59b3273f1c9c_key -iv $encrypted_59b3273f1c9c_iv
  -in ./frontend/utils/pwEncrypt.tar.enc -out ./frontend/utils/pwEncrypt.tar -d
- tar xvf ./frontend/utils/pwEncrypt.tar -C ./frontend/utils


- openssl aes-256-cbc -K $encrypted_a3d7886d982d_key -iv $encrypted_a3d7886d982d_iv
  -in ./backend/udodok-jar.tar.enc -out ./backend/udodok-jar.tar -d
- tar xvf ./backend/udodok-jar.tar -C ./backend

after_success:
- docker build -t woo00oo/udodok-frontend ./frontend
- docker build -t woo00oo/udodok-backend ./backend
- docker build -t woo00oo/udodok-nginx ./nginx

- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

- docker push woo00oo/udodok-frontend
- docker push woo00oo/udodok-backend
- docker push woo00oo/udodok-nginx

deploy:
  provider: elasticbeanstalk 
  region: "ap-northeast-2" 
  app: "udodok-app" 
  env: "Udodokapp-env" 
  bucket_name: elasticbeanstalk-ap-northeast-2-555236258445 
  bucket_path: "udodok-app" 
  on:
    branch: master  
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY