language: generic

sudo: required

services:
- docker

script:
- docker build -t woo00oo/udodok-frontend ./frontend
- docker build -t woo00oo/udodok-backend ./backend
- docker build -t woo00oo/udodok-nginx ./nginx

- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

- docker push woo00oo/udodok-frontend
- docker push woo00oo/udodok-backend
- docker push woo00oo/udodok-nginx

before_install:
- openssl aes-256-cbc -K $encrypted_a3d7886d982d_key -iv $encrypted_a3d7886d982d_iv
  -in udodok-jar.tar.enc -out udodok-jar.tar -d
- tar xvf udodok-jar.tar
