version: "2.4"

services:
  frontend:
    image: woo00oo/udodok-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx: 
    restart: always
    image: woo00oo/udodok-nginx
    ports: 
      - "3000:80"
    links:
      - frontend
      - backend

  backend:
    image: woo00oo/udodok-backend
